apiVersion: v1
kind: Service
metadata:
  name: {{ include "udpsrv.fullname" . }}
  labels:
    {{- include "udpsrv.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 2222
      protocol: UDP
      name: udpsrv
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: udpsrv-tcp
  selector:
    {{- include "udpsrv.selectorLabels" . | nindent 4 }}
